name: linter
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - name: linter
        run: poetry run flake8 brain_games
