name: linter
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: linter
        run: poetry run flake8 brain_games
